shallow_clone: true
skip_tags: true
environment:
  matrix:
    - nodejs_version: '2'
    - nodejs_version: '0'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script: node test.js
